language: rust
rust:
  - stable
env:
  # Test with different FF versions the $CHECKSUM is the output from sha256sum
  - FF_URL="https://download-installer.cdn.mozilla.net/pub/firefox/releases/55.0.3/linux-x86_64/en-US/firefox-55.0.3.tar.bz2" CHECKSUM="f0fd11357de7250660f1a5c5b209c44de1d0f50bb1d3444dd2afad6b41e15b9d  firefox-55.0.3.tar.bz2"
before_script:
  - wget $FF_URL
  - FNAME=$(basename $FF_URL)
  - echo "$CHECKSUM" | sha256sum -c
  - tar axf $FNAME
  - export PATH=$PWD/firefox:$PATH
  - which firefox
  - MOZ_HEADLESS=1 firefox --marionette 2>/dev/null &
script:
  - cargo build --verbose --all
  # firefox can only have one active connection/session
  # disable threading in tests to avoid failures
  - export RUST_TEST_THREADS=1
  - export RUST_LOG=marionette=debug,ff=debug,manual=debug
  - export RUST_BACKTRACE=1
  - export MOZ_HEADLESS=1
  # Some tests in the manual require a running instance
  - export PATH=$PATH:$(pwd)/target/debug
  - ff -vvv start --port 7766
  - export FF_PORT=7766
  - sleep 10
  - cargo test --all --verbose
  # bash tests
  - ff/tests/runner.sh
