language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
env:
  # Test with different FF versions the $CHECKSUM is the output from sha256sum
  - FF_URL="https://download-installer.cdn.mozilla.net/pub/firefox/releases/52.0.2/linux-x86_64/en-US/firefox-52.0.2.tar.bz2" CHECKSUM="a37f817182da13dd34520039da8d0ddeb8bad7dd260ec8fb79c61e770bbaf83f  firefox-52.0.2.tar.bz2"
addons:
  apt:
    packages:
    - firefox
    - xvfb
before_script:
  # start xvfb and firefox to run the tests
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
  - sleep 3 # give xvfb some time to start
  - export DISPLAY=:99.0
  - wget $FF_URL
  - FNAME=$(basename $FF_URL)
  - echo "$CHECKSUM" | sha256sum -c
  - tar axf $FNAME
  - export PATH=$PWD/firefox:$PATH
  - which firefox
  - firefox --marionette &
script:
  - cargo build --verbose --all
  # firefox can only have one active connection/session
  # disable threading in tests to avoid failures
  - export RUST_TEST_THREADS=1
  - export RUST_LOG=marionette=debug,ff=debug
  - export RUST_BACKTRACE=1
  - cargo test --all --verbose
