environment:
  global:
    PROJECT_NAME: ff
  matrix:
    # Stable channel
    - TARGET: i686-pc-windows-gnu
      CHANNEL: stable
    - TARGET: i686-pc-windows-msvc
      CHANNEL: stable

# Install Rust and Cargo
# (Based on from https://github.com/rust-lang/libc/blob/master/appveyor.yml)
install:
  - choco install firefox 
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin;C:\Program Files (x86)\Mozilla Firefox;
  - rustc -Vv
  - cargo -V

build: false

test_script:
  # Run a script instead, appveyor blocks waiting background jobs
  - call ci\appveyor_test.bat

after_test:
  # create a release binary
  - if "%CHANNEL%" == "stable" cargo build --manifest-path ff/Cargo.toml --release

artifacts:
  - path: target/release/ff.exe

cache:
  - 'C:\Users\appveyor\.cargo'

deploy:
  provider: GitHub
  auth_token:
    secure: "5+q/dJRgmj33CNchCfhqjLrzjZyxDrYxmqT4bVf0klqzokPx3qbuSJKlEYjQ4MsE"
  artifact: target/release/ff.exe
  draft: false
  prerelease: false
  force_update: true
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
    TARGET: i686-pc-windows-gnu
    CHANNEL: stable
