environment:
  global:
    PROJECT_NAME: ff
  matrix:
    # Stable channel
    - TARGET: i686-pc-windows-gnu
      CHANNEL: stable
    - TARGET: i686-pc-windows-msvc
      CHANNEL: stable
    # Beta channel
    - TARGET: i686-pc-windows-gnu
      CHANNEL: beta
    - TARGET: i686-pc-windows-msvc
      CHANNEL: beta

# Install Rust and Cargo
# (Based on from https://github.com/rust-lang/libc/blob/master/appveyor.yml)
install:
  - choco install firefox 
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin;C:\Program Files (x86)\Mozilla Firefox;
  - rustc -Vv
  - cargo -V

build: false

test_script:
  # firefox can only have one active connection/session
  # disable threading in tests to avoid failures
  - set RUST_TEST_THREADS=1
  - set RUST_LOG=marionette=debug,ff=debug
  - set RUST_BACKTRACE=1
  # We dont actually run the tests for the marionette crate, just for ff
  - cargo test --manifest-path ff/Cargo.toml --verbose

after_build:
  # create a release binary
  - cargo build --manifest-path ff/Cargo.toml --release

artifacts:
  - path: target/release/ff.exe
