[package]
name = "remotemozdbg"
version = "0.1.0"
authors = ["Rui Abreu Ferreira <raf-ep@gmx.com>"]

[dependencies]
serde_json = "1.0"
log = "0.3"
serde_derive = "1.0"
serde = "1.0"
env_logger = "0.4"

[dev-dependencies]
env_logger = "0.4"
